# Generated by Django 2.2.11 on 2020-03-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
    ]
